### ISSUE TITLE
BUG in GCN step

### ISSUE THREAD

**Issue by Haodong-Yan** [naivate/VS#2]
Hi, your work is exciting, and congratulations on your acceptance into CVPR24. When I test a example image from ECON's example. I got following error in GCN step: 

```
manifold ./results/VS/obj/2adf7e94e9c4dd987007a6661422c452_strech.obj ./results/VS/obj/2adf7e94e9c4dd987007a6661422c452_recon.obj 20000
2adf7e94e9c4dd987007a6661422c452:   0%|                                                                                                              | 0/5 [00:51<?, ?it/s]
Traceback (most recent call last):
  File "/home/lg2/.conda/envs/VS/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lg2/.conda/envs/VS/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data0/lg2/VS/apps/infer.py", line 453, in <module>
    recon_obj = run_test(strechvs_path, in_tensor["normal_F"], in_tensor["normal_B"], feature_fine, feature,
  File "/data0/lg2/VS/Mr/test.py", line 76, in run_test
    data = data_preparation(path, normals_f.cpu(), normals_b.cpu(), feature_fine.cpu(), feature_global.cpu(),
  File "/data0/lg2/VS/Mr/test.py", line 22, in data_preparation
    mesh = manifold_upsample(path, mid_path, Mesh, num_faces=40000, res=20000, simplify=True)
  File "/data0/lg2/VS/Mr/util/util.py", line 103, in manifold_upsample
    m_out = Mesh(save_path, hold_history=True, device=torch.device('cpu'))
  File "/data0/lg2/VS/Mr/models/layers/mesh.py", line 32, in __init__
    self.build_gemm()
  File "/data0/lg2/VS/Mr/models/layers/mesh.py", line 102, in build_gemm
    self.vei = torch.Tensor(np.concatenate(np.array(self.vei)).ravel()).to(self.device).long()
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (20000,) + inhomogeneous part.
```

**Comment by Haodong-Yan** [comment]
Sorry, numpy==1.23.5 works. It's just a numpy version problem.
